
# This compose is intended to set up the latest production version of the app.
# production version is guaranteed to be tested and working.

name: AdventureXP
services:

  # ======= Database ======= #
  mysql:
    image: mysql:latest
    container_name: database
    restart: unless-stopped

    # credentials exposed to git is acceptable as connections are limited to host anyway.
    environment:
      MYSQL_ROOT_PASSWORD: axp
      MYSQL_DATABASE: adventureXP
      MYSQL_USER: axp
      MYSQL_PASSWORD: axp
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    # try to connect as backend
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u axp --password=axp
      retries: 100 # on first setup database may take as long as 60sec to allow connections

    # ======= Backend ======= #
  backend:
    container_name: backend
    build:
      context: github.com/WhiteMonsterEnergy/AdventureBackend.git
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - dbUrl=jdbc:mysql://mysql:3306/adventureXP
      - dbUsername=axp
      - dbPassword=axp
    depends_on:
      mysql:
        condition: service_healthy # do not start backend before database will accept connection

    # ======= Frontend ======= #
  frontend:
    container_name: frontend
    build:
      context: github.com/WhiteMonsterEnergy/AdventureFrontend.git
    ports:
      - "127.0.0.1:8080:8080"

volumes:
  mysql_data:
